apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-crud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-crud
  template:
    metadata:
      labels:
        app: springboot-crud
    spec:
      containers:
        - name: springboot-crud
          image: mariomendonca/springboot-crud:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: db-name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: db-password

#  kubectl scale deployment springboot-crud --replicas=3
