apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: springboot-crud
  template:
    metadata:
      labels:
        app: springboot-crud
    spec:
      containers:
        - name: springboot-crud
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: {{ .Values.env.db.host | quote }}
            - name: DB_PORT
              value: {{ .Values.env.db.port | quote }}
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: db-name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: db-password
